[model]
name = "tobramycini_e100_sched"
path = "./models"

[data]
train_file = "./data/tobramycin_train.csv"
test_file = "./data/tobramycin_test.csv"

[data.columns]
id = "ID"
time = "TIME"
dose = "DOSE"
conc = "CP"
evid = "EVID"
covariates = ["AGE", "SEX", "CLCR"]

[settings.train]
epoch = 100
weight_decay = 1e-3
learning_rate = 1e-3
use_scheduler = true
step_size = 10
gamma = 0.1

[settings.nn]
dim_c = [20, 20, 20]
dim_V = [10]
include_covariates = true
