[model]
name = "test"
path = "./models"

[data]
file = "./data/tobramycin.csv"
inc_cov = true

[data.columns]
id = "ID"
time = "TIME"
dose = "DOSE"
conc = "CP"
evid = "EVID"
covariates = ["AGE", "SEX", "CLCR"]

[settings.train]
pre_train_epoch = 10
train_epoch = 10
finetune_epoch = 10
weight_decay = 0
learning_rate = 1e-3

[settings.nn]
dim_c = [20, 20, 20]
dim_V = [10]
include_covariates = false
