[model]
name = "mavoglurant"
path = "./models"

[data]
train_file = "./data/mavoglurant_train.csv"
test_file = "./data/mavoglurant_test.csv"

[data.columns]
id = "ID"
time = "TIME"
dose = "DOSE"
conc = "DV"
covariates = ["AGE", "SEX", "WT", "HT"]

[settings.train]
epoch = 100
weight_decay = 1e-4
learning_rate = 1e-3
patience = 5
factor = 0.5

[settings.nn]
dim_c = [64, 64, 64]
dim_V = [16]
include_covariates = true
