[model]
name = "warfarin"
path = "./models"

[data]
file = "./data/warfarin_data.csv"
inc_cov = true

[data.columns]
id = "ID"
time = "TIME"
dose = "AMT"
conc = "DV"
# evid = "DVID"
covariates = ["WT", "AGE", "SEX"]

[settings.train]
pre_train_epoch = 10
train_epoch = 100
finetune_epoch = 10
weight_decay = 0.1
learning_rate = 1e-3

[settings.nn]
dim_c = [20, 20, 20]
dim_V = [10, 10]
include_covariates = true
